from __future__ import annotations


ATTENDANCE_BOILERPLATE_FRAGMENTS = (
    "zoom",
    "webinar",
    "teleconference",
    "livestream",
    "live stream",
    "register in advance",
    "meeting link",
    "join by phone",
    "dial",
    "unmute",
    "raise hand",
    "conference room",
    "virtual meeting",
    "meeting will be held",
    "public comment",
    "public participation",
    "speakers will be",
    "called to speak",
    "limit your remarks",
    "time allotted",
    "written communications",
    "options to observe",
    "options to participate",
    "attend in person",
    "appear in person",
    "members of the public",
    "submit comments",
    "email comments",
    "e-mail comments",
    "communication access",
    "americans with disabilities act",
    "ada",
    "accommodation",
    "auxiliary aids",
    "interpreters",
    "disability-related",
)
BOILERPLATE_FRAGMENT_GROUPS = (
    (
        "covid",
        "covid-19",
        "coronavirus",
        "state of emergency",
        "executive order",
        "governor newsom",
        "order no-",
        "order no.",
    ),
    (
        "join the webinar",
        "join by phone",
        "please read the following instructions",
        "please read the instructions carefully",
        "instructions carefully",
        "you will be asked to enter",
        "enter an email address",
        "confirmation email",
        "raise hand",
        "unmute",
        "mute",
        "last four digits",
        "internet browser",
        "browser",
        "microsoft edge",
        "internet explorer",
        "chrome",
        "firefox",
        "safari",
        "h.323",
        "sip",
        "passcode",
        "meeting id",
        "webinar id",
        "registration",
        "register",
    ),
    (
        "communication access",
        "disability",
        "accommodation",
        "auxiliary aids",
        "interpreters",
        "americans with disabilities act",
        "ada",
    ),
    (
        "public advisory",
        "live captioned",
        "captioned broadcast",
        "captioned broadcasts",
        "broadcasts of council meetings",
        "council meetings are available",
        "b-tv",
        "channel 33",
        "kpfa",
        "kpbf",
        "radio 89.3",
        "internet video stream",
        "video stream",
        "webcast",
        "livestream",
        "live stream",
    ),
    (
        "hybrid model",
        "virtual attendance",
        "in-person and virtual",
        "attend this meeting",
        "attend the meeting remotely",
        "meeting will be conducted in a hybrid",
        "to access the meeting",
        "to access the meeting remotely",
        "join from a pc",
        "please use this url",
    ),
    (
        "important notice",
        "any writings or documents provided to a majority",
        "supplemental material to the agendized item",
        "agendized item",
        "made publicly available on the city website",
        "wish to address the planning commission",
        "speaker request card",
        "when you are called, proceed to the podium",
        "any other item not on the agenda",
        "comments to three",
        "for questions on any items in the agenda",
        "meeting agendas and writings distributed",
        "described in the notice",
        "consideration of that item",
        "request card located in front",
        "prior to discussion of the",
        "proceed to the podium",
        "address the planning commission",
        "government code section 84308",
        "levine act",
        "parties to a proceeding involving a license, permit, or other",
        "in accordance with the authority in me vested",
        "i do hereby call the berkeley city council",
        "presiding officer may remove",
        "disrupting the meeting",
        "failure to cease their behavior",
        "this proclamation serves as the official agenda",
        "cause personal notice to be given",
    ),
    (
        "annotated agenda",
        "special meeting of the",
        "calling a special meeting",
        "proclamation",
        "planning commission agenda",
    ),
    (
        "mentimeter",
        "slido",
        "poll",
        "survey",
        "enter code",
        "mobile device",
        "qr code",
    ),
)
