from __future__ import annotations

from pipeline.config_inference import load_inference_config
from pipeline.config_processing import load_processing_config
from pipeline.config_semantic import load_semantic_config
from pipeline.config_startup import load_startup_config
from pipeline.config_table import load_table_config
from pipeline.config_topic_similarity import load_topic_similarity_config


startup_config = load_startup_config()
processing_config = load_processing_config()
inference_config = load_inference_config()
semantic_config = load_semantic_config()
topic_similarity_config = load_topic_similarity_config()
table_config = load_table_config()

STARTUP_PURGE_DERIVED = startup_config.startup_purge_derived
APP_ENV = startup_config.app_env
STARTUP_PURGE_ALLOW_NON_DEV = startup_config.startup_purge_allow_non_dev

MAX_CONTENT_LENGTH = processing_config.max_content_length
MAX_SUMMARY_TEXT_LENGTH = processing_config.max_summary_text_length
NLP_MAX_TEXT_LENGTH = processing_config.nlp_max_text_length
NLP_ENTITY_AGENDA_MAX_TEXT = processing_config.nlp_entity_agenda_max_text
NLP_ENTITY_NONAGENDA_MAX_TEXT = processing_config.nlp_entity_nonagenda_max_text
NLP_ENTITY_PREFIX_FALLBACK_TEXT = processing_config.nlp_entity_prefix_fallback_text
NLP_ENTITY_MIN_CAPITALIZED_NAME_CUES = processing_config.nlp_entity_min_capitalized_name_cues
ENTITY_BACKFILL_IN_PROCESS_THRESHOLD = processing_config.entity_backfill_in_process_threshold
MAX_FILE_SIZE_BYTES = processing_config.max_file_size_bytes
FILE_WRITE_CHUNK_SIZE = processing_config.file_write_chunk_size
DOWNLOAD_TIMEOUT_SECONDS = processing_config.download_timeout_seconds
DOWNLOAD_WORKERS = processing_config.download_workers
MEILISEARCH_BATCH_SIZE = processing_config.meilisearch_batch_size
DOCUMENT_CHUNK_SIZE = processing_config.document_chunk_size
MAX_WORKERS = processing_config.max_workers
PIPELINE_CPU_FRACTION = processing_config.pipeline_cpu_fraction
DB_RETRY_DELAY_MIN = processing_config.db_retry_delay_min
DB_RETRY_DELAY_MAX = processing_config.db_retry_delay_max
EXTRACTION_TERMINAL_FAILURE_MAX_ATTEMPTS = processing_config.extraction_terminal_failure_max_attempts
AGENDA_BATCH_SIZE = processing_config.agenda_batch_size
AGENDA_FALLBACK_MAX_ITEMS_PER_DOC = processing_config.agenda_fallback_max_items_per_doc
AGENDA_FALLBACK_MAX_ITEMS_PER_PAGE_PARAGRAPH = processing_config.agenda_fallback_max_items_per_page_paragraph
AGENDA_FALLBACK_MAX_CONSECUTIVE_REJECTS_PER_PAGE = processing_config.agenda_fallback_max_consecutive_rejects_per_page
AGENDA_SEGMENTATION_MODE = processing_config.agenda_segmentation_mode
AGENDA_MIN_TITLE_CHARS = processing_config.agenda_min_title_chars
AGENDA_MIN_SUBSTANTIVE_DESC_CHARS = processing_config.agenda_min_substantive_desc_chars
AGENDA_TOC_DEDUP_FUZZ = processing_config.agenda_toc_dedup_fuzz
AGENDA_PROCEDURAL_REJECT_ENABLED = processing_config.agenda_procedural_reject_enabled
EXTRACTION_BATCH_SIZE = processing_config.extraction_batch_size
LEGISTAR_EVENT_ITEMS_CAPABILITY_TTL_SECONDS = processing_config.legistar_event_items_capability_ttl_seconds
PIPELINE_ONBOARDING_CITY = processing_config.pipeline_onboarding_city
PIPELINE_ONBOARDING_STARTED_AT_UTC = processing_config.pipeline_onboarding_started_at_utc
PIPELINE_ONBOARDING_DOCUMENT_CHUNK_SIZE = processing_config.pipeline_onboarding_document_chunk_size
PIPELINE_ONBOARDING_MAX_WORKERS = processing_config.pipeline_onboarding_max_workers
PIPELINE_RUNTIME_PROFILE = processing_config.pipeline_runtime_profile
TIKA_TIMEOUT_SECONDS = processing_config.tika_timeout_seconds
TIKA_OCR_FALLBACK_ENABLED = processing_config.tika_ocr_fallback_enabled
TIKA_MIN_EXTRACTED_CHARS_FOR_NO_OCR = processing_config.tika_min_extracted_chars_for_no_ocr
TIKA_PDF_SPACING_TOLERANCE = processing_config.tika_pdf_spacing_tolerance
TIKA_PDF_AVG_CHAR_TOLERANCE = processing_config.tika_pdf_avg_char_tolerance
TIKA_RETRY_BACKOFF_MULTIPLIER = processing_config.tika_retry_backoff_multiplier
TEXT_REPAIR_ENABLE_LLM_ESCALATION = processing_config.text_repair_enable_llm_escalation
TEXT_REPAIR_LLM_MAX_LINES_PER_DOC = processing_config.text_repair_llm_max_lines_per_doc
TEXT_REPAIR_MIN_IMPLAUSIBILITY_SCORE = processing_config.text_repair_min_implausibility_score

LOCAL_AI_ALLOW_MULTIPROCESS = inference_config.local_ai_allow_multiprocess
LOCAL_AI_REQUIRE_SOLO_POOL = inference_config.local_ai_require_solo_pool
LOCAL_AI_BACKEND = inference_config.local_ai_backend
LOCAL_AI_HTTP_API = inference_config.local_ai_http_api
LOCAL_AI_HTTP_BASE_URL = inference_config.local_ai_http_base_url
LOCAL_AI_HTTP_PROFILE = inference_config.local_ai_http_profile
LOCAL_AI_HTTP_TIMEOUT_SECONDS = inference_config.local_ai_http_timeout_seconds
LOCAL_AI_HTTP_TIMEOUT_SEGMENT_SECONDS = inference_config.local_ai_http_timeout_segment_seconds
LOCAL_AI_HTTP_TIMEOUT_SUMMARY_SECONDS = inference_config.local_ai_http_timeout_summary_seconds
LOCAL_AI_HTTP_TIMEOUT_TOPICS_SECONDS = inference_config.local_ai_http_timeout_topics_seconds
AGENDA_SEGMENT_MAINTENANCE_TIMEOUT_SECONDS = inference_config.agenda_segment_maintenance_timeout_seconds
SUMMARY_HYDRATION_MAINTENANCE_TIMEOUT_SECONDS = inference_config.summary_hydration_maintenance_timeout_seconds
LOCAL_AI_HTTP_MAX_RETRIES = inference_config.local_ai_http_max_retries
LOCAL_AI_HTTP_MODEL = inference_config.local_ai_http_model
CITY_SEGMENTATION_WORKERS = inference_config.city_segmentation_workers
LLM_CONTEXT_WINDOW = inference_config.llm_context_window
LLM_SUMMARY_MAX_TEXT = inference_config.llm_summary_max_text
LLM_SUMMARY_MAX_TOKENS = inference_config.llm_summary_max_tokens
LLM_AGENDA_MAX_TEXT = inference_config.llm_agenda_max_text
LLM_AGENDA_MAX_TOKENS = inference_config.llm_agenda_max_tokens
ENABLE_VOTE_EXTRACTION = inference_config.enable_vote_extraction
VOTE_EXTRACTION_MAX_TOKENS = inference_config.vote_extraction_max_tokens
VOTE_EXTRACTION_MIN_TEXT_CHARS = inference_config.vote_extraction_min_text_chars
VOTE_EXTRACTION_CONFIDENCE_THRESHOLD = inference_config.vote_extraction_confidence_threshold
VOTE_EXTRACTION_CONTEXT_BEFORE_CHARS = inference_config.vote_extraction_context_before_chars
VOTE_EXTRACTION_CONTEXT_AFTER_CHARS = inference_config.vote_extraction_context_after_chars
SUMMARY_MIN_CHARS = inference_config.summary_min_chars
SUMMARY_MIN_DISTINCT_TOKENS = inference_config.summary_min_distinct_tokens
SUMMARY_MAX_BOILERPLATE_RATIO = inference_config.summary_max_boilerplate_ratio
TOPICS_MIN_CHARS = inference_config.topics_min_chars
TOPICS_MIN_DISTINCT_TOKENS = inference_config.topics_min_distinct_tokens
SUMMARY_GROUNDING_MIN_COVERAGE = inference_config.summary_grounding_min_coverage
AGENDA_SUMMARY_PROFILE = inference_config.agenda_summary_profile
AGENDA_SUMMARY_MIN_ITEM_DESC_CHARS = inference_config.agenda_summary_min_item_desc_chars
AGENDA_SUMMARY_MAX_BULLETS = inference_config.agenda_summary_max_bullets
AGENDA_SUMMARY_SINGLE_ITEM_MODE = inference_config.agenda_summary_single_item_mode
AGENDA_SUMMARY_TEMPERATURE = inference_config.agenda_summary_temperature
AGENDA_SUMMARY_MAX_INPUT_CHARS = inference_config.agenda_summary_max_input_chars
AGENDA_SUMMARY_MIN_RESERVED_OUTPUT_CHARS = inference_config.agenda_summary_min_reserved_output_chars

SEMANTIC_ENABLED = semantic_config.semantic_enabled
SEMANTIC_BACKEND = semantic_config.semantic_backend
SEMANTIC_MODEL_NAME = semantic_config.semantic_model_name
SEMANTIC_INDEX_DIR = semantic_config.semantic_index_dir
SEMANTIC_CONTENT_MAX_CHARS = semantic_config.semantic_content_max_chars
SEMANTIC_BASE_TOP_K = semantic_config.semantic_base_top_k
SEMANTIC_MAX_TOP_K = semantic_config.semantic_max_top_k
SEMANTIC_FILTER_EXPANSION_FACTOR = semantic_config.semantic_filter_expansion_factor
SEMANTIC_RERANK_CANDIDATE_LIMIT = semantic_config.semantic_rerank_candidate_limit
FEATURE_TRENDS_DASHBOARD = semantic_config.feature_trends_dashboard
LINEAGE_MIN_EDGE_CONFIDENCE = semantic_config.lineage_min_edge_confidence
LINEAGE_REQUIRE_MUTUAL_EDGES = semantic_config.lineage_require_mutual_edges
SEMANTIC_REQUIRE_SINGLE_PROCESS = semantic_config.semantic_require_single_process
SEMANTIC_ALLOW_MULTIPROCESS = semantic_config.semantic_allow_multiprocess
SEMANTIC_REQUIRE_FAISS = semantic_config.semantic_require_faiss

TFIDF_MAX_DF = topic_similarity_config.tfidf_max_df
TFIDF_MIN_DF = topic_similarity_config.tfidf_min_df
TFIDF_NGRAM_RANGE = topic_similarity_config.tfidf_ngram_range
TFIDF_MAX_FEATURES = topic_similarity_config.tfidf_max_features
TOP_KEYWORDS_PER_DOC = topic_similarity_config.top_keywords_per_doc
PROGRESS_LOG_INTERVAL = topic_similarity_config.progress_log_interval
SIMILARITY_CONTENT_LENGTH = topic_similarity_config.similarity_content_length
EMBEDDING_BATCH_SIZE = topic_similarity_config.embedding_batch_size
SIMILARITY_THRESHOLD = topic_similarity_config.similarity_threshold
FAISS_TOP_NEIGHBORS = topic_similarity_config.faiss_top_neighbors
MAX_RELATED_DOCS = topic_similarity_config.max_related_docs

TABLE_ACCURACY_MIN = table_config.table_accuracy_min
TABLE_SCAN_MAX_PAGES = table_config.table_scan_max_pages
TABLE_WORKER_CPU_FRACTION = table_config.table_worker_cpu_fraction
TABLE_PROGRESS_LOG_INTERVAL = table_config.table_progress_log_interval


__all__ = [
    name for name, value in globals().items() if name.isupper() and not name.startswith("_") and not callable(value)
]
