from __future__ import annotations

import math
from collections.abc import Callable, Iterable, Iterator, Mapping
from typing import Protocol

from prometheus_client.core import Metric

from pipeline.metrics_definitions import TPS_BUCKETS, TTFT_BUCKETS
from pipeline.metrics_provider_keys import split_labels_key


class ProviderMetricsRedisClient(Protocol):
    def scan_iter(self, match: str | None = None) -> Iterable[str]: ...

    def get(self, key: str) -> object: ...

    def hgetall(self, key: str) -> Mapping[object, object]: ...


GetRedisClient = Callable[[], ProviderMetricsRedisClient | None]
GetBackendUp = Callable[[], float]
SetBackendUp = Callable[[float], None]

COLLECTOR_READ_ERRORS = (RuntimeError, TypeError, ValueError)


class RedisProviderMetricsCollector:
    """
    Export prefork-safe provider telemetry from Redis into Prometheus exposition.
    """

    def __init__(
        self,
        redis_client_factory: GetRedisClient,
        backend_up_getter: GetBackendUp,
        backend_up_setter: SetBackendUp,
        *,
        read_errors: tuple[type[BaseException], ...] = COLLECTOR_READ_ERRORS,
    ) -> None:
        self._redis_client_factory = redis_client_factory
        self._backend_up_getter = backend_up_getter
        self._backend_up_setter = backend_up_setter
        self._read_errors = read_errors

    def collect(self) -> Iterator[Metric]:
        client = self._redis_client_factory()
        backend_metric = Metric(
            "tc_provider_metrics_backend_up",
            "Whether Redis-backed provider telemetry backend is available (1=yes, 0=no).",
            "gauge",
        )
        backend_metric.add_sample(
            "tc_provider_metrics_backend_up",
            labels={},
            value=float(self._backend_up_getter()),
        )
        yield backend_metric
        if client is None:
            return

        req_metric = Metric("tc_provider_requests_total", "Total inference provider requests.", "counter")
        timeout_metric = Metric("tc_provider_timeouts_total", "Total inference provider timeouts.", "counter")
        retry_metric = Metric("tc_provider_retries_total", "Total inference provider retries.", "counter")
        prompt_metric = Metric(
            "tc_provider_prompt_tokens_total",
            "Total prompt tokens processed by inference provider.",
            "counter",
        )
        completion_metric = Metric(
            "tc_provider_completion_tokens_total",
            "Total completion tokens generated by inference provider.",
            "counter",
        )
        ttft_metric = Metric(
            "tc_provider_ttft_ms",
            "Inference provider time-to-first-token (prompt evaluation) in milliseconds.",
            "histogram",
        )
        tps_metric = Metric(
            "tc_provider_tokens_per_sec",
            "Inference provider completion throughput in tokens per second.",
            "histogram",
        )

        self._add_labeled_counter_samples(
            client,
            req_metric,
            redis_prefix="tc:provider:req_total:",
            sample_name="tc_provider_requests_total",
            expected_parts=4,
        )
        self._add_labeled_counter_samples(
            client,
            timeout_metric,
            redis_prefix="tc:provider:timeouts_total:",
            sample_name="tc_provider_timeouts_total",
            expected_parts=3,
        )
        self._add_labeled_counter_samples(
            client,
            retry_metric,
            redis_prefix="tc:provider:retries_total:",
            sample_name="tc_provider_retries_total",
            expected_parts=3,
        )
        self._add_labeled_counter_samples(
            client,
            prompt_metric,
            redis_prefix="tc:provider:prompt_tokens_total:",
            sample_name="tc_provider_prompt_tokens_total",
            expected_parts=4,
        )
        self._add_labeled_counter_samples(
            client,
            completion_metric,
            redis_prefix="tc:provider:completion_tokens_total:",
            sample_name="tc_provider_completion_tokens_total",
            expected_parts=4,
        )
        self._add_histogram_samples(client, "tc:provider:ttft_ms", ttft_metric, TTFT_BUCKETS)
        self._add_histogram_samples(client, "tc:provider:tps", tps_metric, TPS_BUCKETS)

        yield req_metric
        yield timeout_metric
        yield retry_metric
        yield prompt_metric
        yield completion_metric
        yield ttft_metric
        yield tps_metric

    def _safe_scan(self, client: ProviderMetricsRedisClient, match: str) -> list[str]:
        try:
            return list(client.scan_iter(match=match))
        except self._read_errors:
            self._backend_up_setter(0.0)
            return []

    def _safe_get_float(self, client: ProviderMetricsRedisClient, key: str) -> float:
        try:
            return float(client.get(key) or 0.0)
        except self._read_errors:
            self._backend_up_setter(0.0)
            return 0.0

    def _safe_hgetall(self, client: ProviderMetricsRedisClient, key: str) -> dict[str, object]:
        try:
            return {str(k): v for k, v in (client.hgetall(key) or {}).items()}
        except self._read_errors:
            self._backend_up_setter(0.0)
            return {}

    def _add_labeled_counter_samples(
        self,
        client: ProviderMetricsRedisClient,
        metric: Metric,
        *,
        redis_prefix: str,
        sample_name: str,
        expected_parts: int,
    ) -> None:
        for key in self._safe_scan(client, f"{redis_prefix}*"):
            if not key.startswith(redis_prefix):
                continue
            labels_key = key.split(redis_prefix, 1)[1]
            labels = split_labels_key(labels_key, expected_parts)
            if labels is None:
                continue
            metric.add_sample(sample_name, labels=_provider_sample_labels(labels), value=self._safe_get_float(client, key))

    def _add_histogram_samples(
        self,
        client: ProviderMetricsRedisClient,
        prefix: str,
        metric: Metric,
        buckets: tuple[float, ...],
    ) -> None:
        for bucket_key in self._safe_scan(client, f"{prefix}:bucket:*"):
            if not bucket_key.startswith(f"{prefix}:bucket:"):
                continue
            labels_key = bucket_key.split(f"{prefix}:bucket:", 1)[1]
            labels = split_labels_key(labels_key, 4)
            if labels is None:
                continue
            per_bucket = self._histogram_bucket_values(client, bucket_key)
            cumulative = 0.0
            for upper_bound in buckets:
                le = "+Inf" if math.isinf(upper_bound) else str(float(upper_bound))
                cumulative += per_bucket.get(le, 0.0)
                metric.add_sample(
                    f"{metric.name}_bucket",
                    labels={**_provider_sample_labels(labels), "le": le},
                    value=cumulative,
                )
            self._add_histogram_meta_samples(client, prefix, labels_key, labels, metric)

    def _histogram_bucket_values(self, client: ProviderMetricsRedisClient, bucket_key: str) -> dict[str, float]:
        per_bucket: dict[str, float] = {}
        for raw_bucket, raw_value in self._safe_hgetall(client, bucket_key).items():
            try:
                per_bucket[str(raw_bucket)] = float(raw_value)
            except (TypeError, ValueError):
                self._backend_up_setter(0.0)
        return per_bucket

    def _add_histogram_meta_samples(
        self,
        client: ProviderMetricsRedisClient,
        prefix: str,
        labels_key: str,
        labels: tuple[str, ...],
        metric: Metric,
    ) -> None:
        meta = self._safe_hgetall(client, f"{prefix}:meta:{labels_key}")
        count_value = _float_or_degraded(meta.get("count", 0.0), self._backend_up_setter)
        sum_value = _float_or_degraded(meta.get("sum", 0.0), self._backend_up_setter)
        metric.add_sample(f"{metric.name}_count", labels=_provider_sample_labels(labels), value=count_value)
        metric.add_sample(f"{metric.name}_sum", labels=_provider_sample_labels(labels), value=sum_value)


def _float_or_degraded(raw_value: object, backend_up_setter: SetBackendUp) -> float:
    try:
        return float(raw_value)
    except (TypeError, ValueError):
        backend_up_setter(0.0)
        return 0.0


def _provider_sample_labels(labels: tuple[str, ...]) -> dict[str, str]:
    if len(labels) == 3:
        provider, operation, model = labels
        return {"provider": provider, "operation": operation, "model": model}
    provider, operation, model, outcome = labels
    return {"provider": provider, "operation": operation, "model": model, "outcome": outcome}
