from __future__ import annotations

import math
from typing import Final

from prometheus_client import Counter, Histogram

CELERY_TASK_DURATION_SECONDS = Histogram(
    "tc_celery_task_duration_seconds",
    "Celery task runtime in seconds.",
    labelnames=("task_name", "status"),
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120),
)

CELERY_TASK_FAILURES_TOTAL = Counter(
    "tc_celery_task_failures_total",
    "Total number of Celery task failures.",
    labelnames=("task_name", "exception_type"),
)

CELERY_TASK_RETRIES_TOTAL = Counter(
    "tc_celery_task_retries_total",
    "Total number of Celery task retries.",
    labelnames=("task_name",),
)

TASK_QUEUE_WAIT_SECONDS = Histogram(
    "tc_task_queue_wait_seconds",
    "Celery task queue wait time in seconds from publish to worker start.",
    labelnames=("task_name", "queue"),
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120),
)

PIPELINE_PHASE_DURATION_SECONDS = Histogram(
    "tc_pipeline_phase_duration_seconds",
    "Pipeline phase duration in seconds.",
    labelnames=("phase", "component", "mode", "status"),
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120, 300, 900),
)

LINEAGE_RECOMPUTE_RUNS_TOTAL = Counter(
    "tc_lineage_recompute_runs_total",
    "Total lineage recompute runs executed by Celery.",
)

LINEAGE_CATALOG_UPDATES_TOTAL = Counter(
    "tc_lineage_catalog_updates_total",
    "Total catalog lineage rows updated by lineage recompute.",
)

LINEAGE_COMPONENT_MERGES_TOTAL = Counter(
    "tc_lineage_component_merges_total",
    "Total connected-component lineage merges observed during recompute.",
)

PROVIDER_REQUESTS_TOTAL = Counter(
    "tc_provider_requests_total",
    "Total inference provider requests.",
    labelnames=("provider", "operation", "model", "outcome"),
)

PROVIDER_REQUEST_DURATION_MS = Histogram(
    "tc_provider_request_duration_ms",
    "Inference provider request duration in milliseconds.",
    labelnames=("provider", "operation", "model", "outcome"),
    buckets=(50, 100, 250, 500, 1000, 2500, 5000, 10000, 20000, 45000, 90000),
)

PROVIDER_TTFT_MS = Histogram(
    "tc_provider_ttft_ms",
    "Inference provider time-to-first-token (prompt evaluation) in milliseconds.",
    labelnames=("provider", "operation", "model", "outcome"),
    buckets=(10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000, 20000),
)

PROVIDER_TOKENS_PER_SEC = Histogram(
    "tc_provider_tokens_per_sec",
    "Inference provider completion throughput in tokens per second.",
    labelnames=("provider", "operation", "model", "outcome"),
    buckets=(1, 2, 5, 10, 20, 30, 40, 60, 80, 120, 200),
)

PROVIDER_PROMPT_TOKENS_TOTAL = Counter(
    "tc_provider_prompt_tokens_total",
    "Total prompt tokens processed by inference provider.",
    labelnames=("provider", "operation", "model", "outcome"),
)

PROVIDER_COMPLETION_TOKENS_TOTAL = Counter(
    "tc_provider_completion_tokens_total",
    "Total completion tokens generated by inference provider.",
    labelnames=("provider", "operation", "model", "outcome"),
)

PROVIDER_TIMEOUTS_TOTAL = Counter(
    "tc_provider_timeouts_total",
    "Total inference provider timeouts.",
    labelnames=("provider", "operation", "model"),
)

PROVIDER_RETRIES_TOTAL = Counter(
    "tc_provider_retries_total",
    "Total inference provider retries.",
    labelnames=("provider", "operation", "model"),
)

TTFT_BUCKETS: Final = (
    10.0,
    25.0,
    50.0,
    100.0,
    250.0,
    500.0,
    1000.0,
    2500.0,
    5000.0,
    10000.0,
    20000.0,
    math.inf,
)
TPS_BUCKETS: Final = (1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 60.0, 80.0, 120.0, 200.0, math.inf)
