from __future__ import annotations

from pipeline.summary_hydration_diagnostic_builder import build_summary_hydration_snapshot
from pipeline.summary_hydration_diagnostic_contracts import (
    AGENDA_DOC_KIND,
    AGENDA_SEGMENTATION_BLOCKED_ROOT_CAUSE,
    AGENDA_UNSCHEDULED_ROOT_CAUSE,
    AGENDA_WITH_ITEMS_SAMPLE_BUCKET,
    AGENDA_WITHOUT_ITEMS_SAMPLE_BUCKET,
    BLOCKED_LOW_SIGNAL_PATH,
    ELIGIBLE_AGENDA_SUMMARY_PATH,
    ELIGIBLE_NON_AGENDA_SUMMARY_PATH,
    METRIC_SEMANTICS,
    MISSING_CONTENT_PATH,
    MISSING_SUMMARY_ROOT_CAUSE_RATIO_THRESHOLD,
    NEEDS_SEGMENTATION_PATH,
    NON_AGENDA_SAMPLE_BUCKET,
    NON_AGENDA_UNSCHEDULED_ROOT_CAUSE,
    NO_DOMINANT_BACKLOG_ROOT_CAUSE,
    NULL_SEGMENTATION_STATUS,
    QUALITY_GATE_ROOT_CAUSE,
    UNKNOWN_DOC_KIND,
    AgendaItemModelLike,
    CatalogModelLike,
    DocumentModelLike,
    EventModelLike,
    NonAgendaMissingSummaryRow,
    SummaryHydrationModels,
    SummaryHydrationSampleCatalogIds,
    SummaryHydrationSnapshot,
)
from pipeline.summary_hydration_diagnostic_policy import infer_primary_root_cause, predict_summary_path


__all__ = (
    "AGENDA_DOC_KIND",
    "AGENDA_SEGMENTATION_BLOCKED_ROOT_CAUSE",
    "AGENDA_UNSCHEDULED_ROOT_CAUSE",
    "AGENDA_WITH_ITEMS_SAMPLE_BUCKET",
    "AGENDA_WITHOUT_ITEMS_SAMPLE_BUCKET",
    "BLOCKED_LOW_SIGNAL_PATH",
    "ELIGIBLE_AGENDA_SUMMARY_PATH",
    "ELIGIBLE_NON_AGENDA_SUMMARY_PATH",
    "METRIC_SEMANTICS",
    "MISSING_CONTENT_PATH",
    "MISSING_SUMMARY_ROOT_CAUSE_RATIO_THRESHOLD",
    "NEEDS_SEGMENTATION_PATH",
    "NON_AGENDA_SAMPLE_BUCKET",
    "NON_AGENDA_UNSCHEDULED_ROOT_CAUSE",
    "NO_DOMINANT_BACKLOG_ROOT_CAUSE",
    "NULL_SEGMENTATION_STATUS",
    "QUALITY_GATE_ROOT_CAUSE",
    "UNKNOWN_DOC_KIND",
    "AgendaItemModelLike",
    "CatalogModelLike",
    "DocumentModelLike",
    "EventModelLike",
    "NonAgendaMissingSummaryRow",
    "SummaryHydrationModels",
    "SummaryHydrationSampleCatalogIds",
    "SummaryHydrationSnapshot",
    "build_summary_hydration_snapshot",
    "infer_primary_root_cause",
    "predict_summary_path",
)
